#!/usr/bin/env bash

# Update package repository
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a new configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/conf.d/custom.conf > /dev/null

# Create a "Hello World" webpage
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null

# Restart Nginx
sudo service nginx restart

